query Query {
    playground(id: "aa5607c4-3410-45aa-8df0-a89c072d7eaf") {
        id
        name
        lng
        lat
        status
        smokeFreeDate
        volunteerCount
        votes
        managers {
            id
            username
        }
    }
}