query Query {
    playground(id: "16e43fe5-724f-4720-bcca-34077eb49702") {
        id
        name
        lng
        lat
        status
        smokeFreeDate
        volunteerCount
        votes
    }
}