query Query {
    progress {
        total
        remaining
        smokeFree {
            count
            percentage
        }
        workingOnIt {
            count
            percentage
        }
        smoking {
            count
            percentage
        }
    }
}
